package com.lindzh.mybatis.generator.dao;

import com.lindzh.mybatis.generator.bean.StuCourseTT;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * @author AutoGenerated by lindzh
 * 2015年11月15日 12:19
 */
public interface StuCourseTTDao {

	public int addStuCourseTT(StuCourseTT obj);

	public StuCourseTT getById(@Param("id")long id);
	
	public int updateById(@Param("obj")StuCourseTT obj);
	
	public int deleteById(@Param("id")long id);
	
	public StuCourseTT getByUserAndCourse(@Param("stuId")long stuId,@Param("courseId")long courseId);
	
	
	public int deleteByUserAndCourse(@Param("stuId")long stuId,@Param("courseId")long courseId);
	
	
	public List<StuCourseTT> getListByCourseAndTime(@Param("courseId")long courseId,@Param("limit")int limit,@Param("offset") int offset);
	
	public long getCountByCourseAndTime(@Param("courseId")long courseId);
	
}
