package com.linda.common.mybatis.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * @author AutoGenerated by lindzh
 * 2015年11月15日 10:50
 */
public interface StuCourseDao {

	public int addStuCourse(@Param("obj")StuCourse obj);

	public StuCourse getById(@Param("id")long id);
	
	public int updateById(@Param("obj")StuCourse obj);
	
	public int deleteById(@Param("id")long id);
	
	public StuCourse getByUserAndCourse(@Param("stuId")long stuId,@Param("courseId")long courseId);
	
	public int updateByUserAndCourse(@Param("obj")StuCourse obj);
	
	public int deleteByUserAndCourse(@Param("stuId")long stuId,@Param("courseId")long courseId);
	
	
	public List<StuCourse> getListByCountAndTime(@Param("courseId")long courseId,@Param("addTime")long addTime,@Param("limit")int limit,@Param("offset") int offset);
	
	public long getCountByCountAndTime(@Param("courseId")long courseId,@Param("addTime")long addTime);
	
}
